### ISSUE TITLE
Config not loading

### ISSUE THREAD

**Issue by eirikh1996** [Pulverizer/Movecraft-for-Sponge#17]
Hello, I downloaded this plugin and tried installing it on my Sponge test server. However, this error turns up in console:

`[00:54:59 ERROR] [STDERR]: java.nio.file.NoSuchFileException: C:\Users\eirik\Desktop\Sponge test\config\movecraft\248889249402900movecraft.cfg.tmp
[00:54:59 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at java.nio.file.Files.newOutputStream(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at java.nio.file.Files.newBufferedWriter(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles.createAtomicBufferedWriter(AtomicFiles.java:71)
[00:54:59 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles.lambda$createAtomicWriterFactory$0(AtomicFiles.java:52)
[00:54:59 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:157)
[00:54:59 INFO] [movecraft]: Movecraft Enabled.
[00:54:59 ERROR] [STDERR]:      at io.github.pulverizer.movecraft.Movecraft.onLoad(Movecraft.java:189)
[00:54:59 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Movecraft_onLoad11.handle(Unknown Source)
[00:54:59 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)`

Also, there is no config loading as well

Server details:
Sponge implementation: SpongeVanilla
API version: 7.1.6
Minecraft version: 1.12.2
Operating system: Windows 10
Java version: 1.8

**Comment by Pulverizer** [comment]
Configs don't currently get created automatically.

Here's a download link for now: https://1drv.ms/u/s!An7pkNSr0-ZV5F1yF0egeQyEgtpF?e=tnznas

**Comment by Pulverizer** [comment]
updated link: https://1drv.ms/u/s!An7pkNSr0-ZV5F1oRTrK-M7hw2Ng?e=tqy7lB
