### ISSUE TITLE
Error when trying to move a craft

### ISSUE THREAD

**Issue by eirikh1996** [Pulverizer/Movecraft-for-Sponge#20]
Hello. I tried moving a craft and had clicked the pilot sign. However, the plugin errors when trying to move:

[22:34:20 ERROR] [movecraft]: Internal Error - Proccessor thread encountered an error!
[22:34:20 ERROR] [STDERR]: java.util.NoSuchElementException: No value present
[22:34:20 ERROR] [STDERR]:      at java.util.Optional.get(Unknown Source)
[22:34:20 ERROR] [STDERR]:      at io.github.pulverizer.movecraft.craft.Craft.burnFuel(Craft.java:493)
[22:34:20 ERROR] [STDERR]:      at io.github.pulverizer.movecraft.async.TranslationTask.execute(TranslationTask.java:73)[22:34:20 ERROR] [STDERR]:      at io.github.pulverizer.movecraft.async.AsyncTask.task(AsyncTask.java:34)
[22:34:20 ERROR] [STDERR]:      at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[22:34:20 ERROR] [STDERR]:      at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197)
[22:34:20 ERROR] [STDERR]:      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:34:20 ERROR] [STDERR]:      at java.util.concurrent.FutureTask.run(Unknown Source)
[22:34:20 ERROR] [STDERR]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:34:20 ERROR] [STDERR]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:34:20 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)

**Comment by Pulverizer** [comment]
I think somebody had this before but I can't find the discord chat of it.

I'm not sure why this has occurred.

**Comment by Pulverizer** [comment]
Please ensure there are furnaces detected on your craft.

**Comment by Pulverizer** [comment]
Closing this as I haven't seen it happen in recent versions.
